---
title: Exploring space with Minecraft
hero_image: images/banner.png
description: In this resource you will explore SpaceCRAFT, a winning entry in the Astro Pi competion
original_url: https://raspberrypi.org/learning/exploring-space-with-minecraft
theme: red
duration: 2
listed: false
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-1, manufacture-0, community-0
interests: space, games
technologies: raspberry-pi, electronic-components, python, sense-hat
site_areas: projects
hardware: raspberry-pi, electronic-components, sense-hat
software: python
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: What you will need
- title: Exploring the Sense HAT in Minecraft
- title: 'Challenge: Can you find all of the parts on the Sense HAT?'
- title: SpaceCRAFT - display live data
- title: Capturing data from the Sense HAT
- title: SpaceCRAFT - playback captured data 
- title: 'Challenge: Explore the SpaceCRAFT commands'
- title: What next?
