---
title: Exploring space with Minecraft
hero_image: images/banner.png
description: Explore SpaceCRAFT, a winning Astro Pi entry
original_url: https://raspberrypi.org/learning/exploring-space-with-minecraft
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-1, manufacture-0, community-0
interests: space, games
technologies: raspberry-pi, electronic-components, python, sense-hat
site_areas: projects
hardware: raspberry-pi, electronic-components, sense-hat
software: python
version: 4.0.1
last_tested: 2018-04-25
steps: 
- title: Introduction
- title: What you will need
- title: Exploring the Sense HAT in Minecraft
- title: 'Challenge: find all of the parts on the Sense HAT'
- title: Display live data
- title: Capturing data with the Sense HAT
- title: Play back captured data 
- title: 'Challenge: explore the SpaceCRAFT commands'
- title: What next?
